{% set name = "typeshed-client" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typeshed_client-{{ version }}.tar.gz
  sha256: e63df1e738588ad39f1226de042f4407ab6a99c456f0837063afd83b1415447c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - importlib-resources >=1.4.0

test:
  imports:
    - typeshed_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JelleZijlstra/typeshed_client
  summary: A library for accessing stubs in typeshed.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamjstewart
