{% set name = "typeshed-client" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/typeshed_client-{{ version }}.tar.gz
  sha256: b4e4e3e40dca91ce1a667d2eb0eb350a0a2c0d80e18a232d18857aa61bed3492

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - importlib-resources >=1.4.0

test:
  imports:
    - typeshed_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JelleZijlstra/typeshed_client
  summary: A library for accessing stubs in typeshed.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamjstewart
